---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
  namespace: ic-webapp
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432