---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: ic-webapp
  labels:
    app: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmin
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin@pgadmin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        ports:
        - containerPort: 5050
          name: postgres
        volumeMounts:
        - name: pgadmin-server
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-server
        configMap:
          name: pgadmin-configmap
          items:
          - key: servers.json
            path: servers.json    
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc