---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nodeport
  namespace: ic-webapp
  labels:
    app: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30050