---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: ic-webapp
  labels:
    app: pgadmin
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data_k8s/pgadmin4"