---
apiVersion: v1
kind: Service
metadata:
  namespace: ic-webapp
  name: ic-webapp-nodePort
  labels:
    app: ic-webapp
spec:
  type: NodePort
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080